version: '3.4'

services:
  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  catalogservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  orderingservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

